theme: jekyll-theme-hacker
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
timezone: Europe/London
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
